// Mel Filterbank Coefficients for Whisper (Q15 Fixed-Point)
// Auto-generated by generate_mel_filterbank.py
// For AMD Phoenix NPU - 80 triangular mel filters @ 16 kHz
//
// Specification:
//   - 80 mel bins (Whisper standard)
//   - HTK mel scale: mel = 2595 * log10(1 + f/700)
//   - Triangular filters with ~50% overlap
//   - Q15 format: 1.0 = 32767, 0.5 = 16384
//   - Input: 256 magnitude bins from 512-point FFT
//   - Frequency range: 0-8000 Hz (Nyquist at 16 kHz)

#ifndef MEL_FILTERBANK_COEFFS_H
#define MEL_FILTERBANK_COEFFS_H

#include <stdint.h>

#ifndef NULL
#define NULL ((void*)0)
#endif

// Maximum filter width (in FFT bins)
#define MEL_MAX_FILTER_WIDTH 16
#define MEL_MAX_LEFT_WIDTH 8
#define MEL_MAX_RIGHT_WIDTH 8
#define NUM_MEL_FILTERS 80

// Mel filter structure (Q15 format)
typedef struct {
    uint16_t start_bin;    // First non-zero bin
    uint16_t peak_bin;     // Peak of triangle (weight = 1.0)
    uint16_t end_bin;      // Last non-zero bin
    uint16_t left_width;   // Number of bins in left slope
    uint16_t right_width;  // Number of bins in right slope
    const int16_t* left_slopes;   // Pointer to left slope coefficients (Q15)
    const int16_t* right_slopes;  // Pointer to right slope coefficients (Q15)
} mel_filter_t;

// Filter coefficient arrays
static const int16_t mel_0_right[1] = {
        0
};

static const int16_t mel_1_left[1] = {
    32767
};
static const int16_t mel_1_right[1] = {
        0
};

static const int16_t mel_2_left[1] = {
    32767
};

static const int16_t mel_3_right[1] = {
        0
};

static const int16_t mel_4_left[1] = {
    32767
};
static const int16_t mel_4_right[1] = {
        0
};

static const int16_t mel_5_left[1] = {
    32767
};
static const int16_t mel_5_right[1] = {
        0
};

static const int16_t mel_6_left[1] = {
    32767
};
static const int16_t mel_6_right[1] = {
        0
};

static const int16_t mel_7_left[1] = {
    32767
};
static const int16_t mel_7_right[1] = {
        0
};

static const int16_t mel_8_left[1] = {
    32767
};
static const int16_t mel_8_right[1] = {
        0
};

static const int16_t mel_9_left[1] = {
    32767
};
static const int16_t mel_9_right[1] = {
        0
};

static const int16_t mel_10_left[1] = {
    32767
};
static const int16_t mel_10_right[1] = {
        0
};

static const int16_t mel_11_left[1] = {
    32767
};
static const int16_t mel_11_right[1] = {
        0
};

static const int16_t mel_12_left[1] = {
    32767
};
static const int16_t mel_12_right[1] = {
        0
};

static const int16_t mel_13_left[1] = {
    32767
};
static const int16_t mel_13_right[1] = {
        0
};

static const int16_t mel_14_left[1] = {
    32767
};
static const int16_t mel_14_right[1] = {
        0
};

static const int16_t mel_15_left[1] = {
    32767
};
static const int16_t mel_15_right[1] = {
        0
};

static const int16_t mel_16_left[1] = {
    32767
};
static const int16_t mel_16_right[1] = {
        0
};

static const int16_t mel_17_left[1] = {
    32767
};
static const int16_t mel_17_right[2] = {
    16383,     0
};

static const int16_t mel_18_left[2] = {
    16383, 32767
};
static const int16_t mel_18_right[1] = {
        0
};

static const int16_t mel_19_left[1] = {
    32767
};
static const int16_t mel_19_right[1] = {
        0
};

static const int16_t mel_20_left[1] = {
    32767
};
static const int16_t mel_20_right[2] = {
    16383,     0
};

static const int16_t mel_21_left[2] = {
    16383, 32767
};
static const int16_t mel_21_right[1] = {
        0
};

static const int16_t mel_22_left[1] = {
    32767
};
static const int16_t mel_22_right[1] = {
        0
};

static const int16_t mel_23_left[1] = {
    32767
};
static const int16_t mel_23_right[2] = {
    16383,     0
};

static const int16_t mel_24_left[2] = {
    16383, 32767
};
static const int16_t mel_24_right[1] = {
        0
};

static const int16_t mel_25_left[1] = {
    32767
};
static const int16_t mel_25_right[2] = {
    16383,     0
};

static const int16_t mel_26_left[2] = {
    16383, 32767
};
static const int16_t mel_26_right[2] = {
    16383,     0
};

static const int16_t mel_27_left[2] = {
    16383, 32767
};
static const int16_t mel_27_right[1] = {
        0
};

static const int16_t mel_28_left[1] = {
    32767
};
static const int16_t mel_28_right[2] = {
    16383,     0
};

static const int16_t mel_29_left[2] = {
    16383, 32767
};
static const int16_t mel_29_right[2] = {
    16383,     0
};

static const int16_t mel_30_left[2] = {
    16383, 32767
};
static const int16_t mel_30_right[2] = {
    16383,     0
};

static const int16_t mel_31_left[2] = {
    16383, 32767
};
static const int16_t mel_31_right[2] = {
    16383,     0
};

static const int16_t mel_32_left[2] = {
    16383, 32767
};
static const int16_t mel_32_right[2] = {
    16383,     0
};

static const int16_t mel_33_left[2] = {
    16383, 32767
};
static const int16_t mel_33_right[2] = {
    16383,     0
};

static const int16_t mel_34_left[2] = {
    16383, 32767
};
static const int16_t mel_34_right[2] = {
    16383,     0
};

static const int16_t mel_35_left[2] = {
    16383, 32767
};
static const int16_t mel_35_right[2] = {
    16383,     0
};

static const int16_t mel_36_left[2] = {
    16383, 32767
};
static const int16_t mel_36_right[2] = {
    16383,     0
};

static const int16_t mel_37_left[2] = {
    16383, 32767
};
static const int16_t mel_37_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_38_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_38_right[2] = {
    16383,     0
};

static const int16_t mel_39_left[2] = {
    16383, 32767
};
static const int16_t mel_39_right[2] = {
    16383,     0
};

static const int16_t mel_40_left[2] = {
    16383, 32767
};
static const int16_t mel_40_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_41_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_41_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_42_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_42_right[2] = {
    16383,     0
};

static const int16_t mel_43_left[2] = {
    16383, 32767
};
static const int16_t mel_43_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_44_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_44_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_45_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_45_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_46_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_46_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_47_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_47_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_48_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_48_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_49_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_49_right[4] = {
    24575, 16383,  8191,     0
};

static const int16_t mel_50_left[4] = {
     8191, 16383, 24575, 32767
};
static const int16_t mel_50_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_51_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_51_right[4] = {
    24575, 16383,  8191,     0
};

static const int16_t mel_52_left[4] = {
     8191, 16383, 24575, 32767
};
static const int16_t mel_52_right[3] = {
    21844, 10922,     0
};

static const int16_t mel_53_left[3] = {
    10922, 21844, 32767
};
static const int16_t mel_53_right[4] = {
    24575, 16383,  8191,     0
};

static const int16_t mel_54_left[4] = {
     8191, 16383, 24575, 32767
};
static const int16_t mel_54_right[4] = {
    24575, 16383,  8191,     0
};

static const int16_t mel_55_left[4] = {
     8191, 16383, 24575, 32767
};
static const int16_t mel_55_right[4] = {
    24575, 16383,  8191,     0
};

static const int16_t mel_56_left[4] = {
     8191, 16383, 24575, 32767
};
static const int16_t mel_56_right[4] = {
    24575, 16383,  8191,     0
};

static const int16_t mel_57_left[4] = {
     8191, 16383, 24575, 32767
};
static const int16_t mel_57_right[5] = {
    26213, 19660, 13106,  6553,     0
};

static const int16_t mel_58_left[5] = {
     6553, 13106, 19660, 26213, 32767
};
static const int16_t mel_58_right[4] = {
    24575, 16383,  8191,     0
};

static const int16_t mel_59_left[4] = {
     8191, 16383, 24575, 32767
};
static const int16_t mel_59_right[5] = {
    26213, 19660, 13106,  6553,     0
};

static const int16_t mel_60_left[5] = {
     6553, 13106, 19660, 26213, 32767
};
static const int16_t mel_60_right[5] = {
    26213, 19660, 13106,  6553,     0
};

static const int16_t mel_61_left[5] = {
     6553, 13106, 19660, 26213, 32767
};
static const int16_t mel_61_right[4] = {
    24575, 16383,  8191,     0
};

static const int16_t mel_62_left[4] = {
     8191, 16383, 24575, 32767
};
static const int16_t mel_62_right[5] = {
    26213, 19660, 13106,  6553,     0
};

static const int16_t mel_63_left[5] = {
     6553, 13106, 19660, 26213, 32767
};
static const int16_t mel_63_right[6] = {
    27305, 21844, 16383, 10922,  5461,     0
};

static const int16_t mel_64_left[6] = {
     5461, 10922, 16383, 21844, 27305, 32767
};
static const int16_t mel_64_right[5] = {
    26213, 19660, 13106,  6553,     0
};

static const int16_t mel_65_left[5] = {
     6553, 13106, 19660, 26213, 32767
};
static const int16_t mel_65_right[6] = {
    27305, 21844, 16383, 10922,  5461,     0
};

static const int16_t mel_66_left[6] = {
     5461, 10922, 16383, 21844, 27305, 32767
};
static const int16_t mel_66_right[5] = {
    26213, 19660, 13106,  6553,     0
};

static const int16_t mel_67_left[5] = {
     6553, 13106, 19660, 26213, 32767
};
static const int16_t mel_67_right[6] = {
    27305, 21844, 16383, 10922,  5461,     0
};

static const int16_t mel_68_left[6] = {
     5461, 10922, 16383, 21844, 27305, 32767
};
static const int16_t mel_68_right[6] = {
    27305, 21844, 16383, 10922,  5461,     0
};

static const int16_t mel_69_left[6] = {
     5461, 10922, 16383, 21844, 27305, 32767
};
static const int16_t mel_69_right[6] = {
    27305, 21844, 16383, 10922,  5461,     0
};

static const int16_t mel_70_left[6] = {
     5461, 10922, 16383, 21844, 27305, 32767
};
static const int16_t mel_70_right[7] = {
    28086, 23405, 18724, 14043,  9362,  4681,     0
};

static const int16_t mel_71_left[7] = {
     4681,  9362, 14043, 18724, 23405, 28086, 32767
};
static const int16_t mel_71_right[7] = {
    28086, 23405, 18724, 14043,  9362,  4681,     0
};

static const int16_t mel_72_left[7] = {
     4681,  9362, 14043, 18724, 23405, 28086, 32767
};
static const int16_t mel_72_right[6] = {
    27305, 21844, 16383, 10922,  5461,     0
};

static const int16_t mel_73_left[6] = {
     5461, 10922, 16383, 21844, 27305, 32767
};
static const int16_t mel_73_right[8] = {
    28671, 24575, 20479, 16383, 12287,  8191,  4095,     0
};

static const int16_t mel_74_left[8] = {
     4095,  8191, 12287, 16383, 20479, 24575, 28671, 32767
};
static const int16_t mel_74_right[7] = {
    28086, 23405, 18724, 14043,  9362,  4681,     0
};

static const int16_t mel_75_left[7] = {
     4681,  9362, 14043, 18724, 23405, 28086, 32767
};
static const int16_t mel_75_right[7] = {
    28086, 23405, 18724, 14043,  9362,  4681,     0
};

static const int16_t mel_76_left[7] = {
     4681,  9362, 14043, 18724, 23405, 28086, 32767
};
static const int16_t mel_76_right[8] = {
    28671, 24575, 20479, 16383, 12287,  8191,  4095,     0
};

static const int16_t mel_77_left[8] = {
     4095,  8191, 12287, 16383, 20479, 24575, 28671, 32767
};
static const int16_t mel_77_right[8] = {
    28671, 24575, 20479, 16383, 12287,  8191,  4095,     0
};

static const int16_t mel_78_left[8] = {
     4095,  8191, 12287, 16383, 20479, 24575, 28671, 32767
};
static const int16_t mel_78_right[8] = {
    28671, 24575, 20479, 16383, 12287,  8191,  4095,     0
};

static const int16_t mel_79_left[8] = {
     4095,  8191, 12287, 16383, 20479, 24575, 28671, 32767
};
static const int16_t mel_79_right[8] = {
    28671, 24575, 20479, 16383, 12287,  8191,  4095,     0
};

// Main mel filterbank array
static const mel_filter_t mel_filters[NUM_MEL_FILTERS] = {
    { // Filter 0: 22.1 Hz (35.1 mel)
        .start_bin = 0,
        .peak_bin = 0,
        .end_bin = 1,
        .left_width = 0,
        .right_width = 1,
        .left_slopes = 0,
        .right_slopes = mel_0_right
    },
    { // Filter 1: 44.9 Hz (70.1 mel)
        .start_bin = 0,
        .peak_bin = 1,
        .end_bin = 2,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_1_left,
        .right_slopes = mel_1_right
    },
    { // Filter 2: 68.5 Hz (105.2 mel)
        .start_bin = 1,
        .peak_bin = 2,
        .end_bin = 2,
        .left_width = 1,
        .right_width = 0,
        .left_slopes = mel_2_left,
        .right_slopes = 0
    },
    { // Filter 3: 92.8 Hz (140.2 mel)
        .start_bin = 2,
        .peak_bin = 2,
        .end_bin = 3,
        .left_width = 0,
        .right_width = 1,
        .left_slopes = 0,
        .right_slopes = mel_3_right
    },
    { // Filter 4: 117.8 Hz (175.3 mel)
        .start_bin = 2,
        .peak_bin = 3,
        .end_bin = 4,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_4_left,
        .right_slopes = mel_4_right
    },
    { // Filter 5: 143.7 Hz (210.4 mel)
        .start_bin = 3,
        .peak_bin = 4,
        .end_bin = 5,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_5_left,
        .right_slopes = mel_5_right
    },
    { // Filter 6: 170.3 Hz (245.4 mel)
        .start_bin = 4,
        .peak_bin = 5,
        .end_bin = 6,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_6_left,
        .right_slopes = mel_6_right
    },
    { // Filter 7: 197.8 Hz (280.5 mel)
        .start_bin = 5,
        .peak_bin = 6,
        .end_bin = 7,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_7_left,
        .right_slopes = mel_7_right
    },
    { // Filter 8: 226.2 Hz (315.6 mel)
        .start_bin = 6,
        .peak_bin = 7,
        .end_bin = 8,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_8_left,
        .right_slopes = mel_8_right
    },
    { // Filter 9: 255.5 Hz (350.6 mel)
        .start_bin = 7,
        .peak_bin = 8,
        .end_bin = 9,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_9_left,
        .right_slopes = mel_9_right
    },
    { // Filter 10: 285.7 Hz (385.7 mel)
        .start_bin = 8,
        .peak_bin = 9,
        .end_bin = 10,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_10_left,
        .right_slopes = mel_10_right
    },
    { // Filter 11: 316.8 Hz (420.7 mel)
        .start_bin = 9,
        .peak_bin = 10,
        .end_bin = 11,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_11_left,
        .right_slopes = mel_11_right
    },
    { // Filter 12: 348.9 Hz (455.8 mel)
        .start_bin = 10,
        .peak_bin = 11,
        .end_bin = 12,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_12_left,
        .right_slopes = mel_12_right
    },
    { // Filter 13: 382.1 Hz (490.9 mel)
        .start_bin = 11,
        .peak_bin = 12,
        .end_bin = 13,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_13_left,
        .right_slopes = mel_13_right
    },
    { // Filter 14: 416.3 Hz (525.9 mel)
        .start_bin = 12,
        .peak_bin = 13,
        .end_bin = 14,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_14_left,
        .right_slopes = mel_14_right
    },
    { // Filter 15: 451.5 Hz (561.0 mel)
        .start_bin = 13,
        .peak_bin = 14,
        .end_bin = 15,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_15_left,
        .right_slopes = mel_15_right
    },
    { // Filter 16: 487.9 Hz (596.1 mel)
        .start_bin = 14,
        .peak_bin = 15,
        .end_bin = 16,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_16_left,
        .right_slopes = mel_16_right
    },
    { // Filter 17: 525.5 Hz (631.1 mel)
        .start_bin = 15,
        .peak_bin = 16,
        .end_bin = 18,
        .left_width = 1,
        .right_width = 2,
        .left_slopes = mel_17_left,
        .right_slopes = mel_17_right
    },
    { // Filter 18: 564.2 Hz (666.2 mel)
        .start_bin = 16,
        .peak_bin = 18,
        .end_bin = 19,
        .left_width = 2,
        .right_width = 1,
        .left_slopes = mel_18_left,
        .right_slopes = mel_18_right
    },
    { // Filter 19: 604.1 Hz (701.2 mel)
        .start_bin = 18,
        .peak_bin = 19,
        .end_bin = 20,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_19_left,
        .right_slopes = mel_19_right
    },
    { // Filter 20: 645.4 Hz (736.3 mel)
        .start_bin = 19,
        .peak_bin = 20,
        .end_bin = 22,
        .left_width = 1,
        .right_width = 2,
        .left_slopes = mel_20_left,
        .right_slopes = mel_20_right
    },
    { // Filter 21: 687.9 Hz (771.4 mel)
        .start_bin = 20,
        .peak_bin = 22,
        .end_bin = 23,
        .left_width = 2,
        .right_width = 1,
        .left_slopes = mel_21_left,
        .right_slopes = mel_21_right
    },
    { // Filter 22: 731.7 Hz (806.4 mel)
        .start_bin = 22,
        .peak_bin = 23,
        .end_bin = 24,
        .left_width = 1,
        .right_width = 1,
        .left_slopes = mel_22_left,
        .right_slopes = mel_22_right
    },
    { // Filter 23: 777.0 Hz (841.5 mel)
        .start_bin = 23,
        .peak_bin = 24,
        .end_bin = 26,
        .left_width = 1,
        .right_width = 2,
        .left_slopes = mel_23_left,
        .right_slopes = mel_23_right
    },
    { // Filter 24: 823.6 Hz (876.6 mel)
        .start_bin = 24,
        .peak_bin = 26,
        .end_bin = 27,
        .left_width = 2,
        .right_width = 1,
        .left_slopes = mel_24_left,
        .right_slopes = mel_24_right
    },
    { // Filter 25: 871.8 Hz (911.6 mel)
        .start_bin = 26,
        .peak_bin = 27,
        .end_bin = 29,
        .left_width = 1,
        .right_width = 2,
        .left_slopes = mel_25_left,
        .right_slopes = mel_25_right
    },
    { // Filter 26: 921.5 Hz (946.7 mel)
        .start_bin = 27,
        .peak_bin = 29,
        .end_bin = 31,
        .left_width = 2,
        .right_width = 2,
        .left_slopes = mel_26_left,
        .right_slopes = mel_26_right
    },
    { // Filter 27: 972.7 Hz (981.7 mel)
        .start_bin = 29,
        .peak_bin = 31,
        .end_bin = 32,
        .left_width = 2,
        .right_width = 1,
        .left_slopes = mel_27_left,
        .right_slopes = mel_27_right
    },
    { // Filter 28: 1025.6 Hz (1016.8 mel)
        .start_bin = 31,
        .peak_bin = 32,
        .end_bin = 34,
        .left_width = 1,
        .right_width = 2,
        .left_slopes = mel_28_left,
        .right_slopes = mel_28_right
    },
    { // Filter 29: 1080.1 Hz (1051.9 mel)
        .start_bin = 32,
        .peak_bin = 34,
        .end_bin = 36,
        .left_width = 2,
        .right_width = 2,
        .left_slopes = mel_29_left,
        .right_slopes = mel_29_right
    },
    { // Filter 30: 1136.3 Hz (1086.9 mel)
        .start_bin = 34,
        .peak_bin = 36,
        .end_bin = 38,
        .left_width = 2,
        .right_width = 2,
        .left_slopes = mel_30_left,
        .right_slopes = mel_30_right
    },
    { // Filter 31: 1194.4 Hz (1122.0 mel)
        .start_bin = 36,
        .peak_bin = 38,
        .end_bin = 40,
        .left_width = 2,
        .right_width = 2,
        .left_slopes = mel_31_left,
        .right_slopes = mel_31_right
    },
    { // Filter 32: 1254.2 Hz (1157.0 mel)
        .start_bin = 38,
        .peak_bin = 40,
        .end_bin = 42,
        .left_width = 2,
        .right_width = 2,
        .left_slopes = mel_32_left,
        .right_slopes = mel_32_right
    },
    { // Filter 33: 1316.0 Hz (1192.1 mel)
        .start_bin = 40,
        .peak_bin = 42,
        .end_bin = 44,
        .left_width = 2,
        .right_width = 2,
        .left_slopes = mel_33_left,
        .right_slopes = mel_33_right
    },
    { // Filter 34: 1379.7 Hz (1227.2 mel)
        .start_bin = 42,
        .peak_bin = 44,
        .end_bin = 46,
        .left_width = 2,
        .right_width = 2,
        .left_slopes = mel_34_left,
        .right_slopes = mel_34_right
    },
    { // Filter 35: 1445.4 Hz (1262.2 mel)
        .start_bin = 44,
        .peak_bin = 46,
        .end_bin = 48,
        .left_width = 2,
        .right_width = 2,
        .left_slopes = mel_35_left,
        .right_slopes = mel_35_right
    },
    { // Filter 36: 1513.2 Hz (1297.3 mel)
        .start_bin = 46,
        .peak_bin = 48,
        .end_bin = 50,
        .left_width = 2,
        .right_width = 2,
        .left_slopes = mel_36_left,
        .right_slopes = mel_36_right
    },
    { // Filter 37: 1583.1 Hz (1332.4 mel)
        .start_bin = 48,
        .peak_bin = 50,
        .end_bin = 53,
        .left_width = 2,
        .right_width = 3,
        .left_slopes = mel_37_left,
        .right_slopes = mel_37_right
    },
    { // Filter 38: 1655.3 Hz (1367.4 mel)
        .start_bin = 50,
        .peak_bin = 53,
        .end_bin = 55,
        .left_width = 3,
        .right_width = 2,
        .left_slopes = mel_38_left,
        .right_slopes = mel_38_right
    },
    { // Filter 39: 1729.7 Hz (1402.5 mel)
        .start_bin = 53,
        .peak_bin = 55,
        .end_bin = 57,
        .left_width = 2,
        .right_width = 2,
        .left_slopes = mel_39_left,
        .right_slopes = mel_39_right
    },
    { // Filter 40: 1806.5 Hz (1437.5 mel)
        .start_bin = 55,
        .peak_bin = 57,
        .end_bin = 60,
        .left_width = 2,
        .right_width = 3,
        .left_slopes = mel_40_left,
        .right_slopes = mel_40_right
    },
    { // Filter 41: 1885.7 Hz (1472.6 mel)
        .start_bin = 57,
        .peak_bin = 60,
        .end_bin = 63,
        .left_width = 3,
        .right_width = 3,
        .left_slopes = mel_41_left,
        .right_slopes = mel_41_right
    },
    { // Filter 42: 1967.4 Hz (1507.7 mel)
        .start_bin = 60,
        .peak_bin = 63,
        .end_bin = 65,
        .left_width = 3,
        .right_width = 2,
        .left_slopes = mel_42_left,
        .right_slopes = mel_42_right
    },
    { // Filter 43: 2051.7 Hz (1542.7 mel)
        .start_bin = 63,
        .peak_bin = 65,
        .end_bin = 68,
        .left_width = 2,
        .right_width = 3,
        .left_slopes = mel_43_left,
        .right_slopes = mel_43_right
    },
    { // Filter 44: 2138.6 Hz (1577.8 mel)
        .start_bin = 65,
        .peak_bin = 68,
        .end_bin = 71,
        .left_width = 3,
        .right_width = 3,
        .left_slopes = mel_44_left,
        .right_slopes = mel_44_right
    },
    { // Filter 45: 2228.3 Hz (1612.9 mel)
        .start_bin = 68,
        .peak_bin = 71,
        .end_bin = 74,
        .left_width = 3,
        .right_width = 3,
        .left_slopes = mel_45_left,
        .right_slopes = mel_45_right
    },
    { // Filter 46: 2320.9 Hz (1647.9 mel)
        .start_bin = 71,
        .peak_bin = 74,
        .end_bin = 77,
        .left_width = 3,
        .right_width = 3,
        .left_slopes = mel_46_left,
        .right_slopes = mel_46_right
    },
    { // Filter 47: 2416.3 Hz (1683.0 mel)
        .start_bin = 74,
        .peak_bin = 77,
        .end_bin = 80,
        .left_width = 3,
        .right_width = 3,
        .left_slopes = mel_47_left,
        .right_slopes = mel_47_right
    },
    { // Filter 48: 2514.8 Hz (1718.0 mel)
        .start_bin = 77,
        .peak_bin = 80,
        .end_bin = 83,
        .left_width = 3,
        .right_width = 3,
        .left_slopes = mel_48_left,
        .right_slopes = mel_48_right
    },
    { // Filter 49: 2616.4 Hz (1753.1 mel)
        .start_bin = 80,
        .peak_bin = 83,
        .end_bin = 87,
        .left_width = 3,
        .right_width = 4,
        .left_slopes = mel_49_left,
        .right_slopes = mel_49_right
    },
    { // Filter 50: 2721.2 Hz (1788.2 mel)
        .start_bin = 83,
        .peak_bin = 87,
        .end_bin = 90,
        .left_width = 4,
        .right_width = 3,
        .left_slopes = mel_50_left,
        .right_slopes = mel_50_right
    },
    { // Filter 51: 2829.3 Hz (1823.2 mel)
        .start_bin = 87,
        .peak_bin = 90,
        .end_bin = 94,
        .left_width = 3,
        .right_width = 4,
        .left_slopes = mel_51_left,
        .right_slopes = mel_51_right
    },
    { // Filter 52: 2940.8 Hz (1858.3 mel)
        .start_bin = 90,
        .peak_bin = 94,
        .end_bin = 97,
        .left_width = 4,
        .right_width = 3,
        .left_slopes = mel_52_left,
        .right_slopes = mel_52_right
    },
    { // Filter 53: 3055.9 Hz (1893.3 mel)
        .start_bin = 94,
        .peak_bin = 97,
        .end_bin = 101,
        .left_width = 3,
        .right_width = 4,
        .left_slopes = mel_53_left,
        .right_slopes = mel_53_right
    },
    { // Filter 54: 3174.6 Hz (1928.4 mel)
        .start_bin = 97,
        .peak_bin = 101,
        .end_bin = 105,
        .left_width = 4,
        .right_width = 4,
        .left_slopes = mel_54_left,
        .right_slopes = mel_54_right
    },
    { // Filter 55: 3297.0 Hz (1963.5 mel)
        .start_bin = 101,
        .peak_bin = 105,
        .end_bin = 109,
        .left_width = 4,
        .right_width = 4,
        .left_slopes = mel_55_left,
        .right_slopes = mel_55_right
    },
    { // Filter 56: 3423.3 Hz (1998.5 mel)
        .start_bin = 105,
        .peak_bin = 109,
        .end_bin = 113,
        .left_width = 4,
        .right_width = 4,
        .left_slopes = mel_56_left,
        .right_slopes = mel_56_right
    },
    { // Filter 57: 3553.6 Hz (2033.6 mel)
        .start_bin = 109,
        .peak_bin = 113,
        .end_bin = 118,
        .left_width = 4,
        .right_width = 5,
        .left_slopes = mel_57_left,
        .right_slopes = mel_57_right
    },
    { // Filter 58: 3688.0 Hz (2068.7 mel)
        .start_bin = 113,
        .peak_bin = 118,
        .end_bin = 122,
        .left_width = 5,
        .right_width = 4,
        .left_slopes = mel_58_left,
        .right_slopes = mel_58_right
    },
    { // Filter 59: 3826.7 Hz (2103.7 mel)
        .start_bin = 118,
        .peak_bin = 122,
        .end_bin = 127,
        .left_width = 4,
        .right_width = 5,
        .left_slopes = mel_59_left,
        .right_slopes = mel_59_right
    },
    { // Filter 60: 3969.7 Hz (2138.8 mel)
        .start_bin = 122,
        .peak_bin = 127,
        .end_bin = 132,
        .left_width = 5,
        .right_width = 5,
        .left_slopes = mel_60_left,
        .right_slopes = mel_60_right
    },
    { // Filter 61: 4117.3 Hz (2173.8 mel)
        .start_bin = 127,
        .peak_bin = 132,
        .end_bin = 136,
        .left_width = 5,
        .right_width = 4,
        .left_slopes = mel_61_left,
        .right_slopes = mel_61_right
    },
    { // Filter 62: 4269.5 Hz (2208.9 mel)
        .start_bin = 132,
        .peak_bin = 136,
        .end_bin = 141,
        .left_width = 4,
        .right_width = 5,
        .left_slopes = mel_62_left,
        .right_slopes = mel_62_right
    },
    { // Filter 63: 4426.6 Hz (2244.0 mel)
        .start_bin = 136,
        .peak_bin = 141,
        .end_bin = 147,
        .left_width = 5,
        .right_width = 6,
        .left_slopes = mel_63_left,
        .right_slopes = mel_63_right
    },
    { // Filter 64: 4588.6 Hz (2279.0 mel)
        .start_bin = 141,
        .peak_bin = 147,
        .end_bin = 152,
        .left_width = 6,
        .right_width = 5,
        .left_slopes = mel_64_left,
        .right_slopes = mel_64_right
    },
    { // Filter 65: 4755.7 Hz (2314.1 mel)
        .start_bin = 147,
        .peak_bin = 152,
        .end_bin = 158,
        .left_width = 5,
        .right_width = 6,
        .left_slopes = mel_65_left,
        .right_slopes = mel_65_right
    },
    { // Filter 66: 4928.1 Hz (2349.2 mel)
        .start_bin = 152,
        .peak_bin = 158,
        .end_bin = 163,
        .left_width = 6,
        .right_width = 5,
        .left_slopes = mel_66_left,
        .right_slopes = mel_66_right
    },
    { // Filter 67: 5105.9 Hz (2384.2 mel)
        .start_bin = 158,
        .peak_bin = 163,
        .end_bin = 169,
        .left_width = 5,
        .right_width = 6,
        .left_slopes = mel_67_left,
        .right_slopes = mel_67_right
    },
    { // Filter 68: 5289.4 Hz (2419.3 mel)
        .start_bin = 163,
        .peak_bin = 169,
        .end_bin = 175,
        .left_width = 6,
        .right_width = 6,
        .left_slopes = mel_68_left,
        .right_slopes = mel_68_right
    },
    { // Filter 69: 5478.7 Hz (2454.3 mel)
        .start_bin = 169,
        .peak_bin = 175,
        .end_bin = 181,
        .left_width = 6,
        .right_width = 6,
        .left_slopes = mel_69_left,
        .right_slopes = mel_69_right
    },
    { // Filter 70: 5673.9 Hz (2489.4 mel)
        .start_bin = 175,
        .peak_bin = 181,
        .end_bin = 188,
        .left_width = 6,
        .right_width = 7,
        .left_slopes = mel_70_left,
        .right_slopes = mel_70_right
    },
    { // Filter 71: 5875.3 Hz (2524.5 mel)
        .start_bin = 181,
        .peak_bin = 188,
        .end_bin = 195,
        .left_width = 7,
        .right_width = 7,
        .left_slopes = mel_71_left,
        .right_slopes = mel_71_right
    },
    { // Filter 72: 6083.1 Hz (2559.5 mel)
        .start_bin = 188,
        .peak_bin = 195,
        .end_bin = 201,
        .left_width = 7,
        .right_width = 6,
        .left_slopes = mel_72_left,
        .right_slopes = mel_72_right
    },
    { // Filter 73: 6297.4 Hz (2594.6 mel)
        .start_bin = 195,
        .peak_bin = 201,
        .end_bin = 209,
        .left_width = 6,
        .right_width = 8,
        .left_slopes = mel_73_left,
        .right_slopes = mel_73_right
    },
    { // Filter 74: 6518.6 Hz (2629.7 mel)
        .start_bin = 201,
        .peak_bin = 209,
        .end_bin = 216,
        .left_width = 8,
        .right_width = 7,
        .left_slopes = mel_74_left,
        .right_slopes = mel_74_right
    },
    { // Filter 75: 6746.7 Hz (2664.7 mel)
        .start_bin = 209,
        .peak_bin = 216,
        .end_bin = 223,
        .left_width = 7,
        .right_width = 7,
        .left_slopes = mel_75_left,
        .right_slopes = mel_75_right
    },
    { // Filter 76: 6982.0 Hz (2699.8 mel)
        .start_bin = 216,
        .peak_bin = 223,
        .end_bin = 231,
        .left_width = 7,
        .right_width = 8,
        .left_slopes = mel_76_left,
        .right_slopes = mel_76_right
    },
    { // Filter 77: 7224.7 Hz (2734.8 mel)
        .start_bin = 223,
        .peak_bin = 231,
        .end_bin = 239,
        .left_width = 8,
        .right_width = 8,
        .left_slopes = mel_77_left,
        .right_slopes = mel_77_right
    },
    { // Filter 78: 7475.2 Hz (2769.9 mel)
        .start_bin = 231,
        .peak_bin = 239,
        .end_bin = 247,
        .left_width = 8,
        .right_width = 8,
        .left_slopes = mel_78_left,
        .right_slopes = mel_78_right
    },
    { // Filter 79: 7733.5 Hz (2805.0 mel)
        .start_bin = 239,
        .peak_bin = 247,
        .end_bin = 255,
        .left_width = 8,
        .right_width = 8,
        .left_slopes = mel_79_left,
        .right_slopes = mel_79_right
    }
};

// Helper function to apply single mel filter
// Returns mel energy in Q15 format
static inline int16_t apply_mel_filter(const int16_t* magnitude, const mel_filter_t* filter) {
    int32_t energy = 0;  // Accumulate in Q30 (Q15 × Q15)

    // Apply left slope (rising edge)
    for (int i = 0; i < filter->left_width; i++) {
        int bin_idx = filter->start_bin + i;
        int16_t mag = magnitude[bin_idx];
        int16_t weight = filter->left_slopes[i];

        // Q15 × Q15 = Q30
        energy += (int32_t)mag * (int32_t)weight;
    }

    // Apply right slope (falling edge)
    for (int i = 0; i < filter->right_width; i++) {
        int bin_idx = filter->peak_bin + i;
        int16_t mag = magnitude[bin_idx];
        int16_t weight = filter->right_slopes[i];

        // Q15 × Q15 = Q30
        energy += (int32_t)mag * (int32_t)weight;
    }

    // Convert Q30 back to Q15 (divide by 2^15)
    // Add rounding: (energy + 2^14) >> 15
    int32_t rounded = (energy + (1 << 14)) >> 15;

    // Clamp to INT16 range
    if (rounded > 32767) rounded = 32767;
    if (rounded < -32768) rounded = -32768;

    return (int16_t)rounded;
}

#endif // MEL_FILTERBANK_COEFFS_H
